### ISSUE TITLE
Chef cookbooks support for RHEL/CentOS and Chef 12

### ISSUE THREAD

**Issue by ovaistariq** [crowbar/barclamp-pacemaker#202]
I have reworked the cookbooks to accomplish the following:
- Make them work with RHEL/CentOS versions 6.x
- Make them work with latest release of Chef 11 and 12
- Add test-kitchen tests and test cookbook that sets up and tests a functioning cluster of two nodes using Vagrant. The test cluster manages VIP, DRBD and HAProxy.

I would like to see how I can give this back to the community. I would like to publish in Chef supermarket but wanted to view your opinion.

https://github.com/ovaistariq/cookbook-pacemaker
https://github.com/ovaistariq/cookbook-corosync

**Comment by tboerger** [comment]
Interesting!

**Comment by vuntz** [comment]
Thanks. We probably need to have @aspiers look at your changes, but we'd definitely love to see improvements merged in :-)

**Comment by aspiers** [comment]
Yes, thanks a lot Ovais for sharing - we would indeed love to see these merged in!  However they can't be merged currently because there is no common ancestor commit.  It would be better if you could rebase your changes on top of

* https://github.com/aspiers/cookbook-pacemaker
* https://github.com/aspiers/cookbook-corosync

Let me know if you need help with the git magic required to do this, as it's not obvious.  In fact it may not even be possible to do until I import the latest commits from the barclamp into these repos ... That has been very high on my TODO list for a long time already :-(  We will need to do it via `git subtree`.

**Comment by ovaistariq** [comment]
@aspiers please share your git-foo. I was going to manually merge my changes on top of your cookbooks as like you said there is no common ancestor.

**Comment by aspiers** [comment]
Will do - sorry for the delay but I have only just returned from a 2 week holiday!

**Comment by ovaistariq** [comment]
No problem, but I will soon be going on a 2 week holiday of my own!

**Comment by aspiers** [comment]
I'm back and gradually catching up on email.  I guess you are back soon too so hopefully we can work on this together soon.

**Comment by ovaistariq** [comment]
@aspiers I am back from my vacation today and am slowly catching up. I am all up on working on it together with you. Let me know how/when to start.

**Comment by aspiers** [comment]
OK, I'm a lot closer to being fully caught up so hopefully can provide this info soon.  It's on my TODO list for sure!

**Comment by ovaistariq** [comment]
sounds good!

**Comment by ovaistariq** [comment]
@aspiers I have rebased my changes to Corosync cookbook off crowbar-ha and filed a PR here:
https://github.com/crowbar/crowbar-ha/pull/10

I will do the same with the Pacemaker cookbook.

**Comment by aspiers** [comment]
Great, thanks so much - I will take a look at those ASAP!  So I guess we can close this one now, right?

**Comment by ovaistariq** [comment]
Yes I think this can be closed. I will file a PR separately for the pacemaker cookbook.
